import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import NavBar from '../components/NavBar';
import ProductList from '../components/ProductList';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar/>
      <Hero/>

      <ProductList/>
      <Footer/>
    </div>
  );
}
