import Head from 'next/head'
import Hero from '../src/components/Hero';
import ProductList from '../src/components/ProductList';
import Layout from '../src/layouts/General';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1'
        />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero/>
      <ProductList />
    </Layout>
  );
}
